[pytest]
# 测试用例路径
testpaths = testcases
# 控制台输出详细
addopts = -v -s --html=reports/report.html --self-contained-html
# Python 文件命名规则
python_files = test_*.py
python_classes = Test*
python_functions = test_*
# 日志输出（可选）
log_cli = true
log_cli_level = INFO